services:
  db:
    container_name: maria-db
    image: mariadb
    ports:
      - "5432:5432"
    volumes:
      - maria-db-data:./
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: admin
      MYSQL_HOST: localhost
    networks:
      - backend-network


  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"
    networks:
      - backend-network

networks:
  backend-network:
    name: backend-network
    driver: bridge
