"""Date change and message change

Revision ID: e0961c183b5b
Revises: 06c6895d938e
Create Date: 2024-07-12 17:49:47.107826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0961c183b5b'
down_revision = '06c6895d938e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saludos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saludos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_column('message')

    # ### end Alembic commands ###
